<?php

/*
|--------------------------------------------------------------------------
|   Dais
|--------------------------------------------------------------------------
|
|   This file is part of the Dais Framework package.
|	
|	(c) Vince Kronlein <vince@dais.io>
|	
|	For the full copyright and license information, please view the LICENSE
|	file that was distributed with this source code.
|	
*/

namespace Plugin\Example\Admin\Hooks;
use Dais\Engine\Container;
use Dais\Engine\Plugin;

class ControllerHooks extends Plugin {
    private $script_directory;
    
    public function __construct(Container $app) {
        parent::__construct($app);
        parent::setPlugin('example');
        $this->script_directory = dirname(dirname(__FILE__)) . '/js/';
    }
    
    public function exampleHook($data) {
        $data = $this->language('examplehook', $data);
        
        $data['callback'] = 'Hook replaced callback text.';
        
        $this->theme->loadjs('example', $data, $this->script_directory);
        
        return $data;
    }
    
    public function preHook() {
        $data['prehook'] = 'This alert is generated by a pre-hook from the Example plugin.';
        
        $this->theme->loadjs('prehook', $data, $this->script_directory);
        
        return $data;
    }
}
