#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
|   Dais
|--------------------------------------------------------------------------
|
|   This file is part of the Dais Framework package.
|	
|	(c) Vince Kronlein <vince@dais.io>
|	
|	For the full copyright and license information, please view the LICENSE
|	file that was distributed with this source code.
|	
*/

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
|--------------------------------------------------------------------------
| 	Create The Application
|--------------------------------------------------------------------------
|
| 	First we need to get an application instance. This creates an instance
| 	of the application / container and bootstraps the application so it
| 	is ready to receive HTTP / Console requests from the environment.
|
*/

$app = require __DIR__ . '/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| 	Run The Artisan Application
|--------------------------------------------------------------------------
|
| 	When we run the console application, the current CLI command will be
| 	executed in this console and the response sent back to a terminal
| 	or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(
    'Illuminate\Contracts\Console\Kernel'
);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
